<?php if(isset($this->_error)): ?>
<div class="alert alert-danger" role="alert">
<?php echo $this->_error; ?>
</div>
<?php endif; ?>
<form id="post" method="POST" action="<?php echo BASE_URL . 'post/create'; ?>" enctype="multipart/form-data">
    <input type="hidden" id="save" name="save" value="1" />
    <div class="mb-3">
        <label for="title" class="form-label">Email address</label>
        <input type="text" class="form-control" id="title" name="title" value="<?php if(isset($this->data['title'])) echo $this->data['title']; ?>" placeholder="Add title..." />
    </div>
    <div class="mb-3">
        <label for="body" class="form-label">Body</label>
        <textarea class="form-control" id="body" name="body" rows="3"><?php if(isset($this->data['body'])) echo $this->data['body']; ?></textarea>
    </div>
    <div class="custom-file">
        <input type="file" name="imagen" id="imagen" class="custom-file-input" id="customFile">
        <label class="custom-file-label" for="customFile">Choose file</label>
    </div>
    <button type="submit" class="btn btn-primary">Create Post</button>
</form>