<div class="container">  
  <h2>Test</h2>  
  <?php if(isset($this->posts) && count($this->posts)): ?>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Body</th>
      </tr>
    </thead>
    <tbody>
    <?php for($i = 0; $i < count($this->posts); $i++): ?>
      <tr class="">
        <th scope="row"><?php echo $i; ?></th>
        <td><a href="<?php echo $this->posts[$i]['Rfrnc']; ?>" target="_blank"><?php echo $this->posts[$i]['Ttl']; ?></a></td>
        <td><?php echo $this->posts[$i]['Bdy']; ?></td>        
      </tr>
    <?php endfor; ?>    
    </tbody>
  </table>
  <?php if(isset($this->pagination)): ?>
  <?php echo $this->pagination; ?>
  <?php endif; ?>
  <?php else: ?>
  <p><strong>No data</strong></p>
  <?php endif; ?>
</div>