<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Password</th>
        <th scope="col">MD5</th>
        <th scope="col">SHA256</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td>1234</td>
        <td><?php echo md5(1234); ?></td>
        <td><?php echo hash('sha256', 1234);; ?></td>
      </tr>    
    </tbody>
  </table>

  <h1>Uniquid</h1>
  <h2>Uniqid main: <span>4f6a6d832be79</span></h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Uniqiq</th>
      </tr>
    </thead>
    <tbody>
      <?php for($i = 0; $i < rand(1, 5); $i++): ?>
      <tr>
        <th scope="row"><?php echo $i; ?></th>
        <td><?php echo uniqid(); ?></td>
      </tr>  
      <?php endfor; ?>  
    </tbody>
  </table>
</div>