<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Password</th>
        <th scope="col">MD5</th>
        <th scope="col">SHA256</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td>1234</td>
        <td><?php echo md5(1234); ?></td>
        <td><?php echo hash('sha256', 1234);; ?></td>
      </tr>    
    </tbody>
  </table>
</div>