# --------- <ENGLISH: MODULE. USERS / SPANISH: MÓDULO. USUARIOS> ----------- #

# <ENGLISH: USERS / SPANISH: USUARIOS>
ALTER TABLE `0_Usrs` ADD CONSTRAINT `FrgnKy_Prsn`         FOREIGN KEY(`Rfrnc_Prsn`)   REFERENCES `MIPSS_`.`0_Prsn`(`Rfrnc`)     ON DELETE SET NULL ON UPDATE SET NULL;
ALTER TABLE `0_Usrs` ADD CONSTRAINT `FrgnKy_UsrTyp_Rfrnc` FOREIGN KEY(`UsrTyp_Rfrnc`) REFERENCES `MIPSS_`.`0_TypsUsrs`(`Rfrnc`) ON DELETE SET NULL ON UPDATE SET NULL;
# <.ENGLISH: MODULE / SPANISH: MÓDULOS>

# --------- </ENGLISH: MODULE. USERS / SPANISH: MÓDULO. USUARIOS> ----------- #